routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\BrandsController;
use App\Http\Controllers\Admin\ComponentsController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\ComputersController;
use App\Http\Controllers\Admin\RolesController;
use App\Http\Controllers\CrudController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\ProductController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

});

Route::prefix('admin')->name('admin.')->middleware(['auth:sanctum', 'admin'])->group(function() {
    Route::get('/', [AdminController::class, 'index'])->name('index');
    Route::get('crud/{model}', [CrudController::class, 'index'])->name('crud.index');
    Route::resource('users', UsersController::class);
    Route::resource('roles', RolesController::class);
    Route::resource('computers', ComputersController::class);
    Route::resource('brands', BrandsController::class);
    Route::resource('components', ComponentsController::class);
    Route::resource('products', ProductController::class);
});

app/Models/Computer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Computer extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'slug',
        'comment',
        'case',
        'processor',
        'ram',
        'graphic_card',
        'stokage',
        'is_available',
        'image',
        'price',
    ];

    // Additional model logic and relationships can be defined here
}

app/Http/Controllers/Admin/ComputersController.php
<?php
namespace App\Http\Controllers\Admin;

use \App\Http\Controllers\Controller;
use App\Models\Brand;
use Illuminate\Http\Request;
use \App\Models\Computer;

class ComputersController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Computer::class, 'computer');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        
        return view('admin.computers.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        $computer = new Computer();
        $brands = Brand::select('id', 'name')->pluck('name', 'id');
        return view('admin.computers.form', compact('computer'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required',
            'comment' => 'required',
            'stock_type' => 'required',
            'is_available' => 'required',
            'image' => 'required',

        ]);
        $computer = Computer::create($request->all());
        return redirect()->route('admin.computer.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return void
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Computer $computer
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(Computer $computer)
    {
        $brands = Brand::select('id', 'name')->pluck('name', 'id');
        $computer = Computer::findOrFail($computer);
        return view('admin.computers.form', compact('computer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, ['name' => 'required',
            'slug' => 'required',
            'comment' => 'required',
            'stock_type' => 'required',
            'is_available' => 'required',
            'image' => 'required',
        ]);
        $computer = Computer::findOrFail($id);
        $computer->update($request->all());
        return redirect()->route('admin.computer.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $computer = Computer::findOrFail($id);
        $computer->delete();
        return redirect()->route('admin.computers.index');
    }
}

app/Http/Livewire/ComputerTable.php
<?php
namespace App\Http\Livewire;

use App\Models\Computer;
use App\Models\Brand;
use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\NumberColumn;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;

class ComputerTable extends LivewireDatatable
{
    public $hideable = 'select';

    public function builder()
    {
        return Computer::query()
            ->join('brands', 'brands.id', '=', 'computers.brand_id'); // Join the brands table
    }

    public function columns()
    {
        return [


            Column::callback(['image'], function ($image) {
                return '<img src="' . $image . '" alt="Brand Image" width="100px" height="100px">';
            })->label('Image')->unsortable(),
            Column::name('name')->label('Nom')->searchable(),
            Column::name('case')->label('Boitier')->searchable(),
            Column::name('processor')->label('Processeur')->searchable(),
            Column::name('ram')->label('Ram')->searchable(),
            Column::name('graphic_card')->label('graphic_card')->searchable(),
            Column::name('stokage')->label('Stockage')->searchable(),
            Column::name('brands.name')->label('Marque')->searchable(), // Use brands.name
            Column::name('price')->label('Prix')->searchable(),



            Column::callback(['is_available'], function ($is_available) {
                return $is_available ? 'Vrai' : 'Faux';
            })->label('Disponible')->unsortable(),

            Column::callback(['id'], function ($id) {
                return view('components.table-actions', ['id' => $id, 'routeName' => 'computers']);
            })->unsortable()
        ];
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        $user = auth()->user();
        return view('layouts.app', compact('user'));
    }
}

resources/views/admin/computers/form.blade.php
<x-app-layout>
    <x-slot name="header">
        <h1 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ $computer->id === null ? 'Créer un nouvel élément' : 'Modifier l\'élément' }}
        </h1>
        <nav class="py-3 rounded-md w-full">
            <ol class="list-reset flex">
                <li><a href="{{ route('admin.index') }}" class="text-blue-600 hover:text-blue-700">Accueil</a></li>
                <li><span class="text-gray-500 mx-2">/</span></li>
                <li class="text-gray-500"><a href="{{ route('admin.computers.index') }}" class="text-blue-600 hover:text-blue-700">Liste des computers</a></li>
                <li><span class="text-gray-500 mx-2">/</span></li>
                <li><span class="text-gray-500 mx-2">{{ $computer->id === null ? "Création": 'Modification' }}</span></li>
            </ol>
        </nav>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <x-form action="{{ $computer->id === null ? route('admin.computers.store') : route('admin.computers.update', $computer->id) }}">
                @method($computer->id === null ? 'POST' : 'PUT')
                <x-form-group label="Nom" name="name">
                    <x-input name="name" value="{{ old('name', $computer->name)}}" />
                </x-form-group>

                <x-form-group label="Slug" name="slug">
                    <x-input name="slug"  value="{{ old('slug', $computer->slug) }}" />
                </x-form-group>

                <div class="grid gap-4 grid-cols-3 grid-rows-3">
                    
                    <x-form-group label="Boitier" name="comment">
                        <x-input name="comment"  value="{{ old('comment', $computer->comment) }}" />
                    </x-form-group>

                    <x-form-group label="Processeur" name="stock_type">
                        <x-input name="processeur"  value="{{ old('stock_type', $computer->stock_type) }}" />
                    </x-form-group>

                    <x-form-group label="Ram" name="stock_type">
                        <x-input name="ram"  value="{{ old('stock_type', $computer->stock_type) }}" />
                    </x-form-group>

                    <x-form-group label="Carte Graphique" name="stock_type">
                        <x-input name="stock_type"  value="{{ old('stock_type', $computer->stock_type) }}" />
                    </x-form-group>

                    <x-form-group label="Stokage" name="comment">
                        <x-input name="comment"  value="{{ old('comment', $computer->comment) }}" />
                    </x-form-group>

                    
                    <x-form-group label="Marque PC" name="brand_id">
                        <x-input name="brand"  value="{{ old('brand', $computer->brand) }}" />
                    </x-form-group>
                </div>


                <x-form-group label="Image" name="brand_id">
                    <x-input type="file" name="brand"  value="{{ old('brand', $computer->brand) }}" />
                    
                </x-form-group>

                <x-form-group label="Prix" name="brand_id">
                    <x-input name="brand"  value="{{ old('brand', $computer->brand) }}" />
                </x-form-group>

                <div class="flex space-x-2 justify-center">
                    <button
                    type="button"
                    data-mdb-ripple="true"
                    data-mdb-ripple-color="light"
                    class="inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
                    >{{ $computer->id === null ? 'Créer un nouvel élément' : 'Modifier l\'élément' }}</button>
                </div>

            </x-form>
        </div>
    </div>

</x-app-layout>

resources/views/admin/computers/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h1 class="font-semibold text-xl text-gray-800 leading-tight">
            Liste des __(Computers)
        </h1>
         <nav class="py-3 rounded-md w-full">
            <ol class="list-reset flex">
                <li><a href="{{ route('admin.index') }}" class="text-blue-600 hover:text-blue-700">Accueil</a></li>
                <li><span class="text-gray-500 mx-2">/</span></li>
                <li class="text-gray-500">Liste des pluralModelName</li>
            </ol>
        </nav>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <livewire:computer-table buttons-slot="components.add-button" />
        </div>
    </div>

</x-app-layout>